//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeThi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string ClassId { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
